const js = [
    "Selectors: Universal Selector (*)",
    "Selectors: Type Selectors (element names - e.g., div, p, span)",
    "Selectors: Class Selectors (.classname)",
    "Selectors: ID Selectors (#idname)",
    "Selectors: Attribute Selectors ([attribute])",
    "Selectors: Attribute Selectors ([attribute=value])",
    "Selectors: Attribute Selectors ([attribute~=value])",
    "Selectors: Attribute Selectors ([attribute|=value])",
    "Selectors: Attribute Selectors ([attribute^=value])",
    "Selectors: Attribute Selectors ([attribute$=value])",
    "Selectors: Attribute Selectors ([attribute*=value])",
    "Colors: Color Keywords (e.g., red, blue, green)",
    "Colors: Hexadecimal Colors (#RRGGBB)",
    "Colors: Hexadecimal Colors (#RGB)",
    "Colors: RGB Colors (rgb(R, G, B))",
    "Colors: RGBA Colors (rgba(R, G, B, A))",
    "Colors: HSL Colors (hsl(H, S, L))",
    "Colors: HSLA Colors (hsla(H, S, L, A))",
    "Colors: System Colors (e.g., WindowText, Background) - *Deprecated, avoid using*",
    "Background: Background-color",
    "Background: Background-image (url())",
    "Background: Background-repeat (repeat, repeat-x, repeat-y, no-repeat, space, round)",
    "Background: Background-position (top, bottom, left, right, center, x% y%, x-offset y-offset)",
    "Background: Background-size (auto, cover, contain, x y)",
    "Background: Background-attachment (scroll, fixed, local)",
    "Background: Background (shorthand property)",
    "Background: Background-clip (border-box, padding-box, content-box, text)",
    "Background: Background-origin (border-box, padding-box, content-box)",
    "Background: Background-blend-mode (normal, multiply, screen, overlay, darken, lighten, color-dodge, color-burn, hard-light, soft-light, difference, exclusion, hue, saturation, color, luminosity)",
    "Background: Multiple Backgrounds (comma-separated values)",
    "Typography: Font-family (generic names: serif, sans-serif, monospace, cursive, fantasy)",
    "Typography: Font-family (specific font names, with fallback fonts)",
    "Typography: Font-size (px, em, rem, %, vw, vh, ex, ch, vmin, vmax, small, medium, large, smaller, larger)",
    "Typography: Font-weight (normal, bold, bolder, lighter, 100-900)",
    "Typography: Font-style (normal, italic, oblique)",
    "Typography: Text-align (left, right, center, justify, start, end)",
    "Typography: Text-decoration (none, underline, overline, line-through, wavy)",
    "Typography: Text-decoration-color",
    "Typography: Text-decoration-style",
    "Typography: Text-decoration-thickness",
    "Typography: Text-transform (none, capitalize, uppercase, lowercase)",
    "Typography: Line-height (normal, number, length, %)",
    "Typography: Letter-spacing (normal, length)",
    "Typography: Word-spacing (normal, length)",
    "Typography: Text-shadow (horizontal offset, vertical offset, blur radius, color)",
    "Typography: Text-shadow (multiple shadows)",
    "Typography: Word-wrap (normal, break-word)",
    "Typography: Word-break (normal, break-all, keep-all, break-word)",
    "Typography: Text-overflow (clip, ellipsis, string)",
    "Typography: White-space (normal, nowrap, pre, pre-wrap, pre-line)",
    "Typography: Font-variant (normal, small-caps)",
    "Typography: Font-stretch (ultra-condensed, extra-condensed, condensed, semi-condensed, normal, semi-expanded, expanded, extra-expanded, ultra-expanded)",
    "Typography: Font-kerning (auto, normal, none)",
    "Typography: Font-feature-settings (OpenType features)",
    "Typography: @font-face (src, font-family, font-weight, font-style, unicode-range)",
    "Typography: Web Fonts (Google Fonts, self-hosted fonts)",
    "Typography: Text-indent (length, %)",
    "Typography: Direction (ltr, rtl)",
    "Typography: Unicode-bidi (normal, embed, isolate, bidi-override, isolate-override, plaintext)",
    "Typography: Vertical-align (baseline, sub, super, top, text-top, middle, bottom, text-bottom, length, %)",
    "Box Model: Padding (shorthand: top right bottom left)",
    "Box Model: Padding-top",
    "Box Model: Padding-right",
    "Box Model: Padding-bottom",
    "Box Model: Padding-left",
    "Box Model: Margin (shorthand)",
    "Box Model: Margin-top (auto)",
    "Box Model: Margin-right (auto)",
    "Box Model: Margin-bottom (auto)",
    "Box Model: Margin-left (auto)",
    "Box Model: Border (shorthand: width style color)",
    "Box Model: Border-width (thin, medium, thick, length)",
    "Box Model: Border-style (none, hidden, dotted, dashed, solid, double, groove, ridge, inset, outset)",
    "Box Model: Border-color",
    "Box Model: Border-radius (shorthand: top-left, top-right, bottom-right, bottom-left)",
    "Box Model: Border-top-left-radius",
    "Box Model: Border-top-right-radius",
    "Box Model: Border-bottom-right-radius",
    "Box Model: Border-bottom-left-radius",
    "Box Model: Box-sizing (content-box, border-box, padding-box)",
    "Box Model: Outline (shorthand: width style color)",
    "Box Model: Outline-width (thin, medium, thick, length)",
    "Box Model: Outline-style",
    "Box Model: Outline-color",
    "Box Model: Outline-offset",
    "Box Model: Margin Collapsing",
    "Display: Display: block",
    "Display: Display: inline",
    "Display: Display: inline-block",
    "Display: Display: none",
    "Display: Display: list-item",
    "Display: Display: table",
    "Display: Display: inline-table",
    "Display: Display: table-row",
    "Display: Display: table-cell",
    "Display: Display: table-column",
    "Display: Display: table-row-group",
    "Display: Display: table-header-group",
    "Display: Display: table-footer-group",
    "Display: Display: table-column-group",
    "Display: Display: flex",
    "Display: Display: inline-flex",
    "Display: Display: grid",
    "Display: Display: inline-grid",
    "Display: Display: contents",
    "Display: Display: flow-root",
    "Display: Display: ruby",
    "Display: Display: ruby-base",
    "Display: Display: ruby-text",
    "Display: Display: ruby-base-container",
    "Display: Display: ruby-text-container",
    "List Styling: List-style-type (disc, circle, square, decimal, lower-roman, upper-roman, lower-alpha, upper-alpha, none)",
    "List Styling: List-style-position (inside, outside)",
    "List Styling: List-style-image (url())",
    "List Styling: List-style (shorthand)",
    "Sizing: Width (auto, length, %)",
    "Sizing: Height (auto, length, %)",
    "Sizing: Max-width (none, length, %)",
    "Sizing: Max-height (none, length, %)",
    "Sizing: Min-width (auto, length, %)",
    "Sizing: Min-height (auto, length, %)",
    "Sizing: Object-fit (fill, contain, cover, none, scale-down)",
    "Sizing: Object-position (x y)",
    "Overflow: Overflow (visible, hidden, scroll, auto)",
    "Overflow: Overflow-x",
    "Overflow: Overflow-y",
    "Overflow: Overflow-wrap (normal, break-word)",
    "Overflow: Text-overflow (clip, ellipsis, string)",
    "Overflow: Clip (deprecated - use clip-path)",
    "Overflow: Clip-path (inset, circle, ellipse, polygon, path, url())",
    "Overflow: Mask (url, gradient, image)",
    "Overflow: Mask-mode",
    "Overflow: Mask-size",
    "Overflow: Mask-repeat",
    "Overflow: Mask-position",
    "Overflow: Mask-origin",
    "Overflow: Mask-clip",
    "Positioning: Position: static",
    "Positioning: Position: relative",
    "Positioning: Position: absolute",
    "Positioning: Position: fixed",
    "Positioning: Position: sticky",
    "Positioning: Top",
    "Positioning: Right",
    "Positioning: Bottom",
    "Positioning: Left",
    "Positioning: Z-index (auto, number)",
    "Positioning: Transform (translate, translateX, translateY, scale, scaleX, scaleY, rotate, rotateX, rotateY, rotateZ, skew, skewX, skewY, matrix, perspective)",
    "Positioning: Transform-origin (x y z)",
    "Positioning: Transform-style (flat, preserve-3d)",
    "Positioning: Backface-visibility (visible, hidden)",
    "Positioning: Perspective (length)",
    "Positioning: Perspective-origin (x y)",
    "Floats: Float (left, right, none, inline-start, inline-end)",
    "Floats: Clear (left, right, both, none, inline-start, inline-end)",
    "Floats: Clearfix (implementations to clear floats)",
    "Advanced Selectors: Descendant Combinator (space)",
    "Advanced Selectors: Child Combinator (>)",
    "Advanced Selectors: Adjacent Sibling Combinator (+)",
    "Advanced Selectors: General Sibling Combinator (~)",
    "Pseudo-classes: :hover",
    "Pseudo-classes: :active",
    "Pseudo-classes: :focus",
    "Pseudo-classes: :visited",
    "Pseudo-classes: :link",
    "Pseudo-classes: :first-child",
    "Pseudo-classes: :last-child",
    "Pseudo-classes: :nth-child(even/odd/number/formula)",
    "Pseudo-classes: :nth-last-child(even/odd/number/formula)",
    "Pseudo-classes: :nth-of-type(even/odd/number/formula)",
    "Pseudo-classes: :nth-last-of-type(even/odd/number/formula)",
    "Pseudo-classes: :first-of-type",
    "Pseudo-classes: :last-of-type",
    "Pseudo-classes: :only-child",
    "Pseudo-classes: :only-of-type",
    "Pseudo-classes: :empty",
    "Pseudo-classes: :checked",
    "Pseudo-classes: :disabled",
    "Pseudo-classes: :enabled",
    "Pseudo-classes: :required",
    "Pseudo-classes: :valid",
    "Pseudo-classes: :invalid",
    "Pseudo-classes: :in-range",
    "Pseudo-classes: :out-of-range",
    "Pseudo-classes: :read-only",
    "Pseudo-classes: :read-write",
    "Pseudo-classes: :default",
    "Pseudo-classes: :optional",
    "Pseudo-classes: :placeholder-shown",
    "Pseudo-classes: :fullscreen",
    "Pseudo-classes: :focus-visible",
    "Pseudo-classes: :focus-within",
    "Pseudo-classes: :target",
    "Pseudo-classes: :lang()",
    "Pseudo-classes: :scope",
    "Pseudo-classes: :where()",
    "Pseudo-classes: :is()",
    "Pseudo-classes: :has()",
    "Pseudo-elements: ::before (content)",
    "Pseudo-elements: ::after (content)",
    "Pseudo-elements: ::first-letter",
    "Pseudo-elements: ::first-line",
    "Pseudo-elements: ::selection",
    "Pseudo-elements: ::placeholder",
    "Pseudo-elements: ::marker",
    "Pseudo-elements: ::backdrop",
    "Specificity: Specificity Calculations (ID, Class, Type)",
    "Specificity: !important (use sparingly!)",
    "Inheritance: Inheritance Concept",
    "Inheritance: Inherit Value",
    "Inheritance: Initial Value",
    "Inheritance: Unset Value",
    "Inheritance: Revert Value",
    "Inheritance: All Property",
    "Gradients: Linear Gradients (linear-gradient(angle, color-stop1, color-stop2, ...))",
    "Gradients: Radial Gradients (radial-gradient(shape size at position, color-stop1, color-stop2, ...))",
    "Gradients: Conic Gradients (conic-gradient(angle, color-stop1, color-stop2, ...))",
    "Gradients: Repeating Gradients (repeating-linear-gradient, repeating-radial-gradient, repeating-conic-gradient)",
    "Gradients: Gradient Color Stops (color % or length)",
    "Gradients: Gradient Transparency (rgba, hsla)",
    "Gradients: Gradient Blending",
    "Transitions: Transition (shorthand: property duration timing-function delay)",
    "Transitions: Transition-property (all, none, property names)",
    "Transitions: Transition-duration (time in seconds or milliseconds)",
    "Transitions: Transition-timing-function (ease, linear, ease-in, ease-out, ease-in-out, cubic-bezier())",
    "Transitions: Transition-delay (time in seconds or milliseconds)",
    "Animations: Animation (shorthand: name duration timing-function delay iteration-count direction fill-mode play-state)",
    "Animations: Animation-name (@keyframes name)",
    "Animations: Animation-duration",
    "Animations: Animation-timing-function",
    "Animations: Animation-delay",
    "Animations: Animation-iteration-count (number, infinite)",
    "Animations: Animation-direction (normal, reverse, alternate, alternate-reverse)",
    "Animations: Animation-fill-mode (none, forwards, backwards, both)",
    "Animations: Animation-play-state (running, paused)",
    "Animations: @keyframes (from/0% to/100% or percentage-based steps)",
    "Flexbox: Display: flex",
    "Flexbox: Display: inline-flex",
    "Flexbox: Flex-direction (row, row-reverse, column, column-reverse)",
    "Flexbox: Flex-wrap (nowrap, wrap, wrap-reverse)",
    "Flexbox: Justify-content (flex-start, flex-end, center, space-between, space-around, space-evenly, start, end, left, right)",
    "Flexbox: Align-items (stretch, flex-start, flex-end, center, baseline, start, end, self-start, self-end)",
    "Flexbox: Align-content (stretch, flex-start, flex-end, center, space-between, space-around, space-evenly, start, end, baseline)",
    "Flexbox: Flex-grow (number)",
    "Flexbox: Flex-shrink (number)",
    "Flexbox: Flex-basis (auto, length, %)",
    "Flexbox: Align-self (auto, stretch, flex-start, flex-end, center, baseline, start, end, self-start, self-end)",
    "Flexbox: Order (number)",
    "Flexbox: Flex (shorthand: grow shrink basis)",
    "Flexbox: Flex Shorthand Values (flex: initial, flex: auto, flex: none, flex: [grow] [shrink] [basis])",
    "Flexbox: Gap (row-gap, column-gap, gap)",
    "Grid: Display: grid",
    "Grid: Display: inline-grid",
    "Grid: Grid-template-rows (length, %, fr, auto, min-content, max-content, repeat())",
    "Grid: Grid-template-columns (length, %, fr, auto, min-content, max-content, repeat())",
    "Grid: Grid-template-areas (named areas)",
    "Grid: Grid-template (shorthand for grid-template-rows, grid-template-columns, grid-template-areas)",
    "Grid: Grid-auto-rows (length, %, fr, auto, min-content, max-content)",
    "Grid: Grid-auto-columns (length, %, fr, auto, min-content, max-content)",
    "Grid: Grid-auto-flow (row, column, dense, row dense, column dense)",
    "Grid: Grid-row-start (line number, span number, area name, auto)",
    "Grid: Grid-row-end (line number, span number, area name, auto)",
    "Grid: Grid-column-start (line number, span number, area name, auto)",
    "Grid: Grid-column-end (line number, span number, area name, auto)",
    "Grid: Grid-row (shorthand: start / end)",
    "Grid: Grid-column (shorthand: start / end)",
    "Grid: Grid-area (row-start column-start row-end column-end, named area)",
    "Grid: Grid-gap (shorthand: row-gap column-gap)",
    "Grid: Grid-row-gap",
    "Grid: Grid-column-gap",
    "Grid: Justify-items (stretch, start, end, center)",
    "Grid: Align-items (stretch, start, end, center, baseline)",
    "Grid: Justify-content (start, end, center, stretch, space-around, space-between, space-evenly)",
    "Grid: Align-content (start, end, center, stretch, space-around, space-between, space-evenly)",
    "Grid: Place-items (align-items justify-items)",
    "Grid: Place-content (align-content justify-content)",
    "Grid: Minmax() (min, max size)",
    "Grid: Auto-fit",
    "Grid: Auto-fill",
    "Grid: Grid Line Names (named grid lines)",
    "Grid: Grid Track Sizing (fr unit)",
    "Grid: Grid Placement with Named Lines",
    "Grid: Subgrid",
    "Tables: Border-collapse (collapse, separate)",
    "Tables: Border-spacing (length)",
    "Tables: Caption-side (top, bottom, inline-start, inline-end)",
    "Tables: Empty-cells (show, hide)",
    "Tables: Table-layout (auto, fixed)",
    "Responsive Design: Viewport Meta Tag (width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no)",
    "Responsive Design: @media (screen)",
    "Responsive Design: @media (print)",
    "Responsive Design: @media (orientation: portrait)",
    "Responsive Design: @media (orientation: landscape)",
    "Responsive Design: @media (min-width: px)",
    "Responsive Design: @media (max-width: px)",
    "Responsive Design: @media (min-height: px)",
    "Responsive Design: @media (max-height: px)",
    "Responsive Design: @media (resolution: dpi)",
    "Responsive Design: @media (prefers-color-scheme: light/dark)",
    "Responsive Design: Media Queries Combining Features (and, not, only)",
    "Responsive Design: Mobile-First (starting with smaller screens)",
    "Responsive Design: Desktop-First (starting with larger screens)",
    "Responsive Design: Breakpoints (common screen sizes)",
    "Responsive Design: Fluid Images (max-width: 100%, height: auto)",
    "Responsive Design: Fluid Videos (aspect-ratio + object-fit)",
    "Responsive Design: Picture Element (<picture> tag for responsive images)",
    "Units: Absolute Units (px, pt, pc, in, cm, mm)",
    "Units: Relative Units (em, rem, ch, ex, vw, vh, vmin, vmax, %)",
    "Units: Font-relative Lengths (em, ex, ch, rem)",
    "Units: Viewport-percentage Lengths (vw, vh, vmin, vmax)",
    "Units: calc() (calculations with units)",
    "Variables: CSS Variables (Custom Properties) (--variable-name: value)",
    "Variables: :root (defining global variables)",
    "Variables: var() (using CSS variables)",
    "Variables: var() with fallback value (var(--variable-name, fallback-value))",
    "Variables: CSS Variable Scope (local vs. global)",
    "Variables: JavaScript Access to CSS Variables",
    "Functions: calc() (arithmetic calculations)",
    "Functions: clamp() (restricting a value within a range)",
    "Functions: min() (smallest value)",
    "Functions: max() (largest value)",
    "Functions: rgb()",
    "Functions: rgba()",
    "Functions: hsl()",
    "Functions: hsla()",
    "Functions: color-mix()",
    "Functions: color-contrast()",
    "Filters: Filter (blur, brightness, contrast, drop-shadow, grayscale, hue-rotate, invert, opacity, saturate, sepia)",
    "Filters: Filter Functions (value ranges)",
    "Filters: SVG Filters (advanced filtering)",
    "Blend Modes: Mix-blend-mode (normal, multiply, screen, overlay, darken, lighten, color-dodge, color-burn, hard-light, soft-light, difference, exclusion, hue, saturation, color, luminosity)",
    "Blend Modes: Background-blend-mode (same values as mix-blend-mode)",
    "Clipping: Clip (deprecated - use clip-path)",
    "Clipping: Clip-path (polygon(), circle(), ellipse(), inset(), path(), url())",
    "Clipping: Clip-path Units",
    "Masking: Mask-image (url(), gradient, none)",
    "Masking: Mask-mode (luminance, alpha, match-source)",
    "Masking: Mask-size",
    "Masking: Mask-repeat",
    "Masking: Mask-position",
    "Masking: Mask-origin",
    "Masking: Mask-clip",
    "Masking: Mask-composite",
    "Counters: Counter-reset (identifier number)",
    "Counters: Counter-increment (identifier number)",
    "Counters: Content (counter(identifier), counters(identifier, string))",
    "Columns: Columns (shorthand: column-width column-count)",
    "Columns: Column-width (length)",
    "Columns: Column-count (number)",
    "Columns: Column-gap (length)",
    "Columns: Column-rule (shorthand: width style color)",
    "Columns: Column-span (none, all)",
    "Columns: Column-fill (auto, balance)",
    "Columns: Break-before (auto, avoid, always, left, right, page, column, region)",
    "Columns: Break-after (auto, avoid, always, left, right, page, column, region)",
    "Columns: Break-inside (auto, avoid, avoid-page, avoid-column, avoid-region)",
    "Scroll Snap: Scroll-snap-type (none, x mandatory, y mandatory, both mandatory, x proximity, y proximity, both proximity)",
    "Scroll Snap: Scroll-snap-align (start, end, center, none)",
    "Scroll Snap: Scroll-snap-stop (normal, always)",
    "Scroll Snap: Scroll-margin",
    "Accessibility: Semantic HTML (using correct HTML elements)",
    "Accessibility: ARIA Attributes (role, aria-label, aria-labelledby, aria-describedby, aria-hidden)",
    "Accessibility: Contrast (sufficient contrast between text and background)",
    "Accessibility: Keyboard Navigation (focus indicators, logical tab order)",
    "Accessibility: Focus Indicators (visible focus styles)",
    "Accessibility: Skip Links (skip to main content)",
    "Accessibility: Alt Text (for images)",
    "Accessibility: Labels for Forms (using <label> elements)",
    "Accessibility: Accessible Color Palettes",
    "Accessibility: Using Heading Structure Correctly (<h1> to <h6>)",
    "Accessibility: Accessible Tables (using <th> elements, scope attribute)",
    "Accessibility: Accessibility Tree",
    "Performance: Will-change (optimize animations and transforms)",
    "Performance: Contain (layout, paint, size, content)",
    "Performance: Content-visibility (auto, visible, hidden, paint-only)",
    "CSS-in-JS: Styled Components",
    "CSS-in-JS: Emotion",
    "CSS-in-JS: JSS",
    "CSS Modules: CSS Modules Syntax",
    "CSS Modules: Importing CSS Modules in JavaScript",
    "Shadow DOM: Shadow DOM basics",
    "Shadow DOM: Slots",
    "Shadow DOM: Styling",
    "Custom Properties: CSS Custom Properties (Variables)",
    "Custom Properties: Using Javascript to access and modify variables",
        "Animations: Animation Events (animationstart, animationend, animationiteration)",
    "Animation: Keyframe Selectors (from, to, percentages)",
    "Animation: Easing Functions (Cubic Bezier)",
    "Animation: Animating CSS Grid Properties",
    "Animation: Animating CSS Variables",
    "Animation: Combining Transitions and Animations",
    "Animation: Pausing and Resuming Animations with JavaScript",
    "Animation: Synchronizing Multiple Animations",
    "Interaction Media Features: pointer (none, coarse, fine)",
    "Interaction Media Features: hover (none, hover)",
    "Cursor: Cursor Property (auto, default, pointer, crosshair, text, wait, help, move, zoom-in, zoom-out, grab, grabbing, etc.)",
    "Pointer Events: pointer-events (auto, none, visiblePainted, visibleFill, visibleStroke, visible, painted, fill, stroke, all)",
    "Resize: Resize Property (none, both, horizontal, vertical, block, inline)",
    "User Select: user-select (auto, text, none, all)",
    "Appearance: Appearance Property (none, auto, button, textfield, menulist-button, searchfield, textarea, etc.) - *Browser-Specific, use with caution*",
    "Box Decoration Break: box-decoration-break (slice, clone)",
    "Caret Color: caret-color (color)",
    "Forced Colors: Forced Colors Mode (Windows High Contrast Mode)",
    "Logical Properties and Values: inset-inline-start, inset-inline-end, inset-block-start, inset-block-end, margin-inline-start, margin-inline-end, margin-block-start, margin-block-end, padding-inline-start, padding-inline-end, padding-block-start, padding-block-end, border-inline-start, border-inline-end, border-block-start, border-block-end",
    "Writing Modes: writing-mode (horizontal-tb, vertical-rl, vertical-lr)",
    "Text Orientation: text-orientation (mixed, upright, sideways-right, sideways-left, use-glyph-orientation)",
    "Text Combine Upright: text-combine-upright (none, all, digits)",
    "Shape: Basic Shapes (circle(), ellipse(), inset(), polygon(), path())",
    "Shape: Shape-outside (margin-box, border-box, padding-box, content-box, url(), basic-shape)",
    "Shape: Shape-margin",
    "Shape: Shape-image-threshold",
    "Filter Effects: FeColorMatrix Filter",
    "Filter Effects: FeGaussianBlur Filter",
    "Filter Effects: FeOffset Filter",
    "Filter Effects: FeBlend Filter",
    "Filter Effects: FeComponentTransfer Filter",
    "Filter Effects: FeComposite Filter",
    "Filter Effects: FeConvolveMatrix Filter",
    "Filter Effects: FeDiffuseLighting Filter",
    "Filter Effects: FeDisplacementMap Filter",
    "Filter Effects: FeFlood Filter",
    "Filter Effects: FeImage Filter",
    "Filter Effects: FeMerge Filter",
    "Filter Effects: FeMorphology Filter",
    "Filter Effects: FeSpecularLighting Filter",
    "Filter Effects: FeTile Filter",
    "Filter Effects: FeTurbulence Filter",
    "Masking: SVG Masks",
    "Masking: CSS Masks",
    "Image Rendering: image-rendering (auto, crisp-edges, pixelated)",
    "Object View Box: object-view-box",
    "Overflow Anchor: overflow-anchor (auto, none)",
    "Overscroll Behavior: overscroll-behavior (auto, contain, none)",
    "Print Styles: @page (size, margin, bleeding)",
    "Print Styles: Page Breaks (break-before, break-after, break-inside)",
    "Print Styles: Widows and Orphans",
    "Print Styles: Marks",
    "Font Loading API: FontFace API",
    "Font Loading API: Font Loading Events",
    "Font Display: font-display (auto, block, swap, fallback, optional)",
    "Math Functions: Trigonometric Functions (sin(), cos(), tan(), asin(), acos(), atan(), atan2())",
    "Math Functions: Exponential Functions (pow(), sqrt(), hypot(), log(), exp())",
    "Math Functions: Numeric Functions (round(), trunc(), floor(), ceil(), abs(), sign())",
	"CSS Nesting: CSS Nesting using the & selector",
    "Subgrid: CSS Grid Subgrid Layouts",
    "Container Queries: @container (size, inline-size)",
    "Container Queries: Container-type (size, inline-size, normal)",
    "Cascade Layers: @layer",
    "Custom Highlight API: ::highlight() Pseudo-element",
    "Accent Color: accent-color",
    "Houdini: CSS Painting API (Paint Worklets)",
    "Houdini: CSS Layout API (Layout Worklets)",
    "Houdini: CSS Typed OM (Typed Object Model)",
    "Houdini: CSS Properties and Values API (@property)",
    "Houdini: Animation Worklet (Animation Worklets)",
    "Houdini: Font Metrics API",
	"CSS Modules: Composing Styles",
    "CSS Modules: Global Keywords (:global, :local)",
	"Shadow DOM: Constructable Stylesheets",
	"CSS Containment: Contain Property (none, layout, paint, size, content, strict)",
	"CSS Nesting: Using @nest Rule",
	"View Transitions: view-transition-name Property",
	"View Transitions: View Transition Pseudo-elements (::view-transition, ::view-transition-group(), ::view-transition-image-pair(), ::view-transition-new(), ::view-transition-old())",
	"Scoped CSS: CSS Scopes",
	"CSS Anchors: anchor-name, anchor-default, position-try",
	"Scripting: CSSOM (CSS Object Model)",
	"Interactivity: Show and Hide API"
];

console.log(js); 